version: "3"
services:
  app:
    image: node:20-bullseye
    command: yarn dev
    environment:
      TZ: Asia/Tokyo
      SLACK_SIGNING_SECRET: $SLACK_SIGNING_SECRET
      SLACK_BOT_TOKEN: $SLACK_BOT_TOKEN
      SLACK_APP_TOKEN: $SLACK_APP_TOKEN
      NOTION_TOKEN: $NOTION_TOKEN
      REDIS_HOST: redis
    volumes:
      - .:/app
    working_dir: /app
  redis:
    image: redis:7.2-alpine
    ports:
      - 6379:6379
