name: release
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docker-image:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest version
        id: latest_version
        run: |
          echo 'version=v0.1.0' > $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          # https://github.com/docker/build-push-action/issues/820
          provenance: false
          tags: |
            ghcr.io/${{ github.actor }}/notion-bot:latest
            ghcr.io/${{ github.actor }}/notion-bot:${{ steps.latest_version.outputs.version }}
          labels: |
            org.opencontainers.image.name=notion-bot
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.latest_version.outputs.version }}
            org.opencontainers.image.source=https://github.com/litencatt/notion-bot
